name: postsubmit
on:
  push:
    branches: [ main ]
    paths: 
      - '**/**'            
      - '!config/**'    
      # - 'config/components/edge-iam-v2/targets'  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3